spring:
  application:
    name: department-service

  #import configuration details for department service in following file path
  config:
    import: "optional:configserver:http://localhost:8088/"
